%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-mrpt-sensors
Version:        0.2.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mrpt_sensors package

License:        BSD
URL:            https://github.com/mrpt-ros-pkg/mrpt_sensors/
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jazzy-ament-lint-auto
Requires:       ros-jazzy-ament-lint-common
Requires:       ros-jazzy-mrpt-generic-sensor
Requires:       ros-jazzy-mrpt-sensor-bumblebee-stereo
Requires:       ros-jazzy-mrpt-sensor-gnss-nmea
Requires:       ros-jazzy-mrpt-sensor-gnss-novatel
Requires:       ros-jazzy-mrpt-sensor-imu-taobotics
Requires:       ros-jazzy-mrpt-sensorlib
Requires:       ros-jazzy-ros-workspace
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-ament-lint-auto
BuildRequires:  ros-jazzy-ament-lint-common
BuildRequires:  ros-jazzy-mrpt-generic-sensor
BuildRequires:  ros-jazzy-mrpt-sensor-bumblebee-stereo
BuildRequires:  ros-jazzy-mrpt-sensor-gnss-nmea
BuildRequires:  ros-jazzy-mrpt-sensor-gnss-novatel
BuildRequires:  ros-jazzy-mrpt-sensor-imu-taobotics
BuildRequires:  ros-jazzy-mrpt-sensorlib
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
ROS nodes for various robotics sensors via mrpt-hwdrivers. Metapackage for all
mrpt_sensor packages.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Fri Aug 09 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.2.2-1
- Autogenerated by Bloom

* Wed Jul 03 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.2.1-1
- Autogenerated by Bloom

* Fri Apr 19 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.1.0-2
- Autogenerated by Bloom

* Thu Mar 28 2024 Jose-Luis Blanco-Claraco <jlblanco@ual.es> - 0.1.0-1
- Autogenerated by Bloom

