%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/iron/.*$
%global __requires_exclude_from ^/opt/ros/iron/.*$

Name:           ros-iron-mrpt-sensor-imu-taobotics
Version:        0.2.3
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mrpt_sensor_imu_taobotics package

License:        BSD
URL:            https://github.com/mrpt-ros-pkg/mrpt_sensors
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-iron-ament-lint-auto
Requires:       ros-iron-ament-lint-common
Requires:       ros-iron-cv-bridge
Requires:       ros-iron-geometry-msgs
Requires:       ros-iron-mrpt-libhwdrivers
Requires:       ros-iron-mrpt-libros-bridge
Requires:       ros-iron-mrpt-msgs
Requires:       ros-iron-mrpt-sensorlib
Requires:       ros-iron-nav-msgs
Requires:       ros-iron-rclcpp
Requires:       ros-iron-rclcpp-components
Requires:       ros-iron-sensor-msgs
Requires:       ros-iron-std-msgs
Requires:       ros-iron-stereo-msgs
Requires:       ros-iron-tf2
Requires:       ros-iron-tf2-ros
Requires:       ros-iron-ros-workspace
BuildRequires:  ros-iron-ament-cmake
BuildRequires:  ros-iron-ament-lint-auto
BuildRequires:  ros-iron-ament-lint-common
BuildRequires:  ros-iron-cv-bridge
BuildRequires:  ros-iron-geometry-msgs
BuildRequires:  ros-iron-mrpt-libhwdrivers
BuildRequires:  ros-iron-mrpt-libros-bridge
BuildRequires:  ros-iron-mrpt-msgs
BuildRequires:  ros-iron-mrpt-sensorlib
BuildRequires:  ros-iron-nav-msgs
BuildRequires:  ros-iron-rclcpp
BuildRequires:  ros-iron-rclcpp-components
BuildRequires:  ros-iron-ros-environment
BuildRequires:  ros-iron-sensor-msgs
BuildRequires:  ros-iron-std-msgs
BuildRequires:  ros-iron-stereo-msgs
BuildRequires:  ros-iron-tf2
BuildRequires:  ros-iron-tf2-ros
BuildRequires:  ros-iron-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
ROS node for Taobotics USB IMUs (based on mrpt-hwdrivers)

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/iron" \
    -DAMENT_PREFIX_PATH="/opt/ros/iron" \
    -DCMAKE_PREFIX_PATH="/opt/ros/iron" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/iron

%changelog
* Sun Sep 01 2024 José Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 0.2.3-1
- Autogenerated by Bloom

* Fri Aug 09 2024 José Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 0.2.2-1
- Autogenerated by Bloom

* Wed Jul 03 2024 José Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 0.2.1-1
- Autogenerated by Bloom

* Mon May 20 2024 José Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 0.2.0-1
- Autogenerated by Bloom

